package com.cafebaby.cafewechat.mapper;

import com.cafebaby.cafewechat.pojo.ChatMsgs;
import com.cafebaby.cafewechat.pojo.ChatMsgsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatMsgsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    long countByExample(ChatMsgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    int deleteByExample(ChatMsgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    int insert(ChatMsgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    int insertSelective(ChatMsgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    List<ChatMsgs> selectByExample(ChatMsgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    ChatMsgs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") ChatMsgs record, @Param("example") ChatMsgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    int updateByExample(@Param("record") ChatMsgs record, @Param("example") ChatMsgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    int updateByPrimaryKeySelective(ChatMsgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    int updateByPrimaryKey(ChatMsgs record);
}