package com.cafebaby.cafewechat.mapper;

import com.cafebaby.cafewechat.pojo.ChatUsers;
import com.cafebaby.cafewechat.pojo.ChatUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Jul 06 09:35:39 CST 2019
     */
    long countByExample(ChatUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Jul 06 09:35:39 CST 2019
     */
    int deleteByExample(ChatUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Jul 06 09:35:39 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Jul 06 09:35:39 CST 2019
     */
    int insert(ChatUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Jul 06 09:35:39 CST 2019
     */
    int insertSelective(ChatUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Jul 06 09:35:39 CST 2019
     */
    List<ChatUsers> selectByExample(ChatUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Jul 06 09:35:39 CST 2019
     */
    ChatUsers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Jul 06 09:35:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") ChatUsers record, @Param("example") ChatUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Jul 06 09:35:39 CST 2019
     */
    int updateByExample(@Param("record") ChatUsers record, @Param("example") ChatUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Jul 06 09:35:39 CST 2019
     */
    int updateByPrimaryKeySelective(ChatUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Jul 06 09:35:39 CST 2019
     */
    int updateByPrimaryKey(ChatUsers record);
}