package com.cafebaby.cafewechat.mapper;

import com.cafebaby.cafewechat.pojo.MyFriends;
import com.cafebaby.cafewechat.pojo.MyFriendsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyFriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    long countByExample(MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    int deleteByExample(MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    int insert(MyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    int insertSelective(MyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    List<MyFriends> selectByExample(MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    MyFriends selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") MyFriends record, @Param("example") MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    int updateByExample(@Param("record") MyFriends record, @Param("example") MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    int updateByPrimaryKeySelective(MyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    int updateByPrimaryKey(MyFriends record);
}