package com.cafebaby.cafewechat.pojo;

import java.io.Serializable;
import java.util.Date;

public class ChatMsgs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.id
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.send_user_id
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    private Long sendUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.accept_user_id
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    private Long acceptUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.sign_flag
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    private Integer signFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.create_time
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.id
     *
     * @return the value of chat_msg.id
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.id
     *
     * @param id the value for chat_msg.id
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.send_user_id
     *
     * @return the value of chat_msg.send_user_id
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    public Long getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.send_user_id
     *
     * @param sendUserId the value for chat_msg.send_user_id
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    public void setSendUserId(Long sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.accept_user_id
     *
     * @return the value of chat_msg.accept_user_id
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    public Long getAcceptUserId() {
        return acceptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.accept_user_id
     *
     * @param acceptUserId the value for chat_msg.accept_user_id
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    public void setAcceptUserId(Long acceptUserId) {
        this.acceptUserId = acceptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.msg
     *
     * @return the value of chat_msg.msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.msg
     *
     * @param msg the value for chat_msg.msg
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.sign_flag
     *
     * @return the value of chat_msg.sign_flag
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    public Integer getSignFlag() {
        return signFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.sign_flag
     *
     * @param signFlag the value for chat_msg.sign_flag
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    public void setSignFlag(Integer signFlag) {
        this.signFlag = signFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.create_time
     *
     * @return the value of chat_msg.create_time
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.create_time
     *
     * @param createTime the value for chat_msg.create_time
     *
     * @mbg.generated Sat Jul 06 09:33:37 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}