package com.cafebaby.cafewechat.pojo;

import java.io.Serializable;

public class MyFriends implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_friends.id
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_friends.my_user_id
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    private Long myUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_friends.my_friend_user_id
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    private Long myFriendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_friends
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_friends.id
     *
     * @return the value of my_friends.id
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_friends.id
     *
     * @param id the value for my_friends.id
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_friends.my_user_id
     *
     * @return the value of my_friends.my_user_id
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    public Long getMyUserId() {
        return myUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_friends.my_user_id
     *
     * @param myUserId the value for my_friends.my_user_id
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    public void setMyUserId(Long myUserId) {
        this.myUserId = myUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_friends.my_friend_user_id
     *
     * @return the value of my_friends.my_friend_user_id
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    public Long getMyFriendUserId() {
        return myFriendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_friends.my_friend_user_id
     *
     * @param myFriendUserId the value for my_friends.my_friend_user_id
     *
     * @mbg.generated Sat Jul 06 09:05:19 CST 2019
     */
    public void setMyFriendUserId(Long myFriendUserId) {
        this.myFriendUserId = myFriendUserId;
    }
}